# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
gems:
  - jekyll-paginate

# Permalinks
permalink: /:year/:month/:title/

# Setup
title: Lazy Project
description: 'a place for potato chips.'
url: https://blog.l4ys.tw
baseurl: /

author:
  name: 'Lays'
  url: https://blog.l4ys.tw/

paginate: 5
excerpt_separator: '<!--more-->'

disqus: lazyproject
google_analytics: UA-158274645-1

